### ISSUE TITLE
Add support for 8296

### ISSUE THREAD

**Issue by Toast-er** [svenpetersen1965/PET-Diagnostic-Clip#1]
I would like to suggest to add support for the 8296 to the diagnostic box.
This would mean the addition of a special user port dongle with connection to the expansion bus, two datasette port dongles and a DB-25 keyboard dongle.
I have a complete and working 8296 diagnostic box set and would like to help, if needed.

**Comment by svenpetersen1965** [comment]
Sounds like a good idea. I don’t own a 8296, though. How could we procede?

**Comment by Toast-er** [comment]
Great!
I think we can get it working together, since I have a 8296 and the original diag set.
Lets start with some information exchange - see attached file. :)

I'm not familiar with github, is there a option for private messages?
 
![CBM8296-Diagnostic](https://user-images.githubusercontent.com/76742590/233855084-cd260630-41db-4526-a9a2-d99c5c5a627f.jpg)

**Comment by Toast-er** [comment]
Attached the wrong file, new try...
[CBM 8296 Diagnostic.zip](https://github.com/svenpetersen1965/PET-Diagnostic-Clip/files/11304372/CBM.8296.Diagnostic.zip)

**Comment by svenpetersen1965** [comment]
We should go email. http://guitarsite.de/p4.htmHere you find mine.Mit freundlichen Grüßen Sven Petersen 
null
